# Generated by Django 5.1.1 on 2024-09-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_rename_categorie_book_category_alter_book_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
